version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
  - package-ecosystem: npm
    directory: /packages/vue-quill
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
  - package-ecosystem: npm
    directory: /docs
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
  - package-ecosystem: npm
    directory: /demo
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
  - package-ecosystem: npm
    directory: /examples/vite-app
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
